README.md
build.gradle
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/VirtusizeApi.kt
sampleappjava/build.gradle

Fix Parameters to support i18n language attribution

Update parameters sent to widget

---

build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/BrowserIdentifier.kt
libsource/src/main/java/com/virtusize/libsource/CallbackHandler.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/data/VirtusizeEndpoint.kt
libsource/src/main/java/com/virtusize/libsource/data/pojo/Data.kt
libsource/src/main/java/com/virtusize/libsource/data/pojo/ProductCheckResponse.kt
libsource/src/main/java/com/virtusize/libsource/data/pojo/ProductMetaDataHintsResponse.kt
libsource/src/main/java/com/virtusize/libsource/data/pojo/UserData.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeButtonStyle.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeEnvironment.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeError.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeEvent.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeMessageHandler.kt
libsource/src/main/java/com/virtusize/libsource/model/VirtusizeProduct.kt
libsource/src/main/java/com/virtusize/libsource/ui/FitIllustratorButton.kt
libsource/src/main/java/com/virtusize/libsource/ui/FitIllustratorView.kt
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Update the comments for clarity

Update the comments

---

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt

Add the missing header field of “x-vs-bid” to the POST request

Fix the problem of not having a fixed browser ID for the given app

---

build.gradle
gradle.properties
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/CallbackHandler.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeError.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeOrder.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeOrderItem.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/Store.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/UserData.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/DataJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/ProductCheckJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/ProductMetaDataHintsJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/StoreJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/UserDataJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/VirtusizeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/main/java/com/virtusize/libsource/ui/FitIllustratorButton.kt
libsource/src/main/java/com/virtusize/libsource/ui/FitIllustratorView.kt
sampleAppKotlin/build.gradle
sampleAppKotlin/src/main/java/com/virtusize/android/App.kt
sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt
sampleappjava/build.gradle
sampleappjava/src/main/java/com/virtusize/sampleappjava/App.java
sampleappjava/src/main/java/com/virtusize/sampleappjava/MainActivity.java
sampleappjava/src/main/res/layout/activity_main.xml

Create the order method in the SDK

---

README.md
build.gradle
libsource/build.gradle
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Bump to 1.6.1

---

README.md
build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/parsers/StoreJsonParser.kt
libsource/src/test/java/com/virtusize/libsource/TestFixtures.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/data/remote/parsers/StoreJsonParserTest.kt
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Hotfix: Fix null region value

---

README.md
build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/CallbackHandler.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeError.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeErrorType.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeOrder.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeOrderItem.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/ui/FitIllustratorButton.kt
libsource/src/test/java/com/virtusize/libsource/data/local/VirtusizeOrderItemTest.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
sampleAppKotlin/build.gradle
sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt
sampleappjava/build.gradle
sampleappjava/src/main/java/com/virtusize/sampleappjava/MainActivity.java

Hotfix: Fix the order API errors for version 1.x.x

---

libsource/src/main/java/com/virtusize/libsource/CallbackHandler.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeError.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/BrandSizingJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductSizeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductTypeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductAdditionalInfoJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductMetaJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/BrandSizing.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/Measurement.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/ProductSize.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/ProductType.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProduct.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProductAdditionalInfo.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProductMeta.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/Weight.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeButtonView.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPage.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeRelativeLayoutView.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeView.kt
libsource/src/main/java/com/virtusize/libsource/util/Extensions.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt

Feature: Document the code for InPage SDK

---

README.md
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeEnvironment.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Bump version 1.7: Change the fit illustrator URL

---

README.md
build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeButton.kt
sampleAppKotlin/build.gradle
sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt
sampleappjava/build.gradle
sampleappjava/src/main/java/com/virtusize/sampleappjava/MainActivity.java

Feature: Update README.md with the InPage integration guide

---

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/BrandSizingJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/DataJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/I18nLocalizationJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/JsonUtils.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductCheckJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductMetaDataHintsJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductSizeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductTypeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductAdditionalInfoJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductMetaJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/UserBodyProfileJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/VirtusizeEventJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/VirtusizeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/UserBodyProfile.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/data/parsers/UserBodyProfileJsonParserTest.kt
libsource/src/test/java/com/virtusize/libsource/fixtures/TestFixtures.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt

Feature:  API integration to get user body measurement data

---

build.gradle
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/StoreProductFitInfo.kt
libsource/src/main/java/com/virtusize/libsource/data/local/UserProductRecommendedSize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeErrorType.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeMessageHandler.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductTypeJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/ProductType.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiResponse.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeButton.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageMini.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageStandard.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeView.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeWebView.kt
libsource/src/main/java/com/virtusize/libsource/util/VirtusizeUtils.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/data/parsers/ProductTypeJsonParserTest.kt
libsource/src/test/java/com/virtusize/libsource/fixtures/ProductFixtures.kt
libsource/src/test/java/com/virtusize/libsource/util/VirtusizeUtilsTest.kt
sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt
sampleappjava/src/main/java/com/virtusize/sampleappjava/MainActivity.java

Feature: Implement the functions to find best-matched product

---

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/SizeComparisonRecommendedSize.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/I18nLocalizationJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/BrandSizing.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/I18nLocalization.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/Product.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProductAdditionalInfo.kt
libsource/src/main/java/com/virtusize/libsource/util/Constants.kt
libsource/src/main/java/com/virtusize/libsource/util/Extensions.kt
libsource/src/main/java/com/virtusize/libsource/util/VirtusizeUtils.kt
libsource/src/main/res/values-ja/strings.xml
libsource/src/main/res/values-ko/strings.xml
libsource/src/main/res/values/strings.xml
libsource/src/test/java/com/virtusize/libsource/data/parsers/I18nLocalizationJsonParserTest.kt
libsource/src/test/java/com/virtusize/libsource/data/remote/ProductTest.kt
libsource/src/test/resources/i18n_en.json
libsource/src/test/resources/i18n_jp.json
libsource/src/test/resources/i18n_ko.json

Feature: Implement the logic to get recommendation texts

---

README-JP.md
README.md

[README](https://github.com/virtusize/integration_android/blob/6755ec92ea1b3f47fd8bfe53575fabc89eda4534/README-JP.md)

Feature: Add JP README

---

README-JP.md
README.md
build.gradle
libsource/build.gradle
libsource/src/main/res/layout/web_activity.xml
libsource/src/main/res/values/styles.xml
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Release: 2.0.5

---

libsource/src/main/java/com/virtusize/libsource/SharedPreferencesHelper.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizeBuilder.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeParams.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/UserSessionInfoJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/data/remote/UserSessionInfo.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeWebView.kt

Feature: Send the session data to the web view

---

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/data/local/BodyProfileRecommendedSizeParams.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/test/java/com/virtusize/libsource/data/local/BodyProfileRecommendedSizeParamsTests.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt

Feature: Update get-size endpoint

---

build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/CallbackHandler.kt
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizePresenter.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizeRepository.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeErrorType.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeOrderItem.kt
libsource/src/main/java/com/virtusize/libsource/data/parsers/ProductCheckJsonParser.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeAPIService.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiResponse.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageStandard.kt
libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageStandardViewModel.kt
libsource/src/main/java/com/virtusize/libsource/util/Extensions.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeAPIServiceTest.kt

Feature: Refactoring

---

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizeBuilder.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizePresenter.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizeRepository.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeEvent.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeParams.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/main/java/com/virtusize/libsource/util/Extensions.kt

**User Added Product**
**User Updated Body Measurements (Create Silhouette)**
**User Updated Body Measurements (Edit Silhouette)**
**User Changed Recommendation Type from body to compareProduct**
**User Changed Recommendation Type from compareProduct to Body**
**User Selected Product**
**User Deleted Data**
**User Logged In**
**User Logged Out**

Feature: InPage Display Logic

---

README-JP.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/main/res/values-ja/strings.xml
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

InPage SDK release 2.1 including some fixes:

InPage SDK release: 2.1

---

README.md
build.gradle
libsource/build.gradle
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeEnvironment.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt
libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt
libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
sampleAppKotlin/build.gradle
sampleappjava/build.gradle

Release: 1.7.1 Update PDC URL

---

README-JP.md
README.md
libsource/src/main/java/com/virtusize/libsource/Virtusize.kt
libsource/src/main/java/com/virtusize/libsource/VirtusizeRepository.kt
libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeMessageHandler.kt
libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt
libsource/src/main/java/com/virtusize/libsource/util/VirtusizeUtils.kt
sampleAppKotlin/build.gradle
sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt
sampleappjava/build.gradle
sampleappjava/src/main/java/com/virtusize/sampleappjava/MainActivity.java

Hofix/2.1.1: Fix Crashes

---

build.gradle
sampleAppKotlin/src/main/AndroidManifest.xml
sampleappjava/src/main/AndroidManifest.xml
virtusize/build.gradle
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt

Add virtusize-auth back using Maven Repository

Integrate virtusize-auth:0.0.2

---

CHANGELOG.md
README-COMPOSE.md
README-JP.md
README.md
sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/App.kt
sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/MainActivity.kt
sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/ProductActivity.kt
sampleappcompose/src/main/java/com/virtusize/sampleapp/compose/VirtusizeSampleApp.kt
virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeButton.kt

[NSDK-196] Update README for Jetpack Compose UI Components

---

CHANGELOG.md
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApi.kt
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeEndpoint.kt
virtusize-core/src/main/java/com/virtusize/android/util/Constants.kt
virtusize-core/src/test/java/com/virtusize/android/network/VirtusizeApiTest.kt
virtusize/src/main/java/com/virtusize/android/data/local/VirtusizeStoreRepository.kt
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeFitIllustratorFragment.kt
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
virtusize/src/main/java/com/virtusize/android/util/VirtusizeUtils.kt

https://github.com/user-attachments/assets/17cba934-0d91-4e33-ac47-3a0e3677f93b

[NSDK-217] Update the WebView URL - Client Specific

---

.githooks/pre-push
CHANGELOG.md
README-JP.md
README.md
buildSrc/src/main/java/com/virtusize/android/constants/Constants.kt
gradle/libs.versions.toml
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApi.kt
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApiResponseFormat.kt
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApiTask.kt
virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeEndpoint.kt
virtusize-core/src/main/java/com/virtusize/android/util/Constants.kt
virtusize-core/src/test/java/com/virtusize/android/data/local/BodyProfileRecommendedSizeParamsTests.kt
virtusize-core/src/test/java/com/virtusize/android/data/local/VirtusizeOrderItemTest.kt
virtusize-core/src/test/java/com/virtusize/android/data/local/VirtusizeOrderTest.kt
virtusize-core/src/test/java/com/virtusize/android/fixtures/ProductFixtures.kt
virtusize-core/src/test/java/com/virtusize/android/network/VirtusizeApiTaskTest.kt
virtusize-core/src/test/java/com/virtusize/android/network/VirtusizeApiTest.kt
virtusize/src/main/java/com/virtusize/android/data/local/VirtusizeStoreRepository.kt
virtusize/src/main/java/com/virtusize/android/network/VirtusizeAPIService.kt
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeFitIllustratorFragment.kt
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
virtusize/src/main/java/com/virtusize/android/util/VirtusizeUtils.kt
virtusize/src/test/java/com/virtusize/android/network/VirtusizeAPIServiceTest.kt

[Release] 2.7.0

---

README.md
gradle/wrapper/gradle-wrapper.properties

Explain the current situation of the code
- Unclear how to setup git-hooks and run linter

Add Contributing section to README 

---

CHANGELOG.md
gradle/libs.versions.toml
virtusize/src/main/java/com/virtusize/android/data/local/VirtusizeParams.kt
virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
virtusize/src/main/java/com/virtusize/android/util/VirtusizeUtils.kt

- Facebook/Google/LINE authentication doesn't work

SNS Auth fixes

---

CHANGELOG.md
README.md
sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/WebAppActivity.kt
virtusize-auth/src/main/java/com/virtusize/android/auth/utils/Extensions.kt
virtusize-auth/src/main/java/com/virtusize/android/auth/utils/VirtusizeUriHelper.kt

- No easy way to specify custom branch for WebView-native apps

Allow to specify branch for WebView-native apps

---

README-COMPOSE.md
README-JP.md
README.md

Explain the current situation of the code
- The SNS authentication guide is in the separate file in VirtusizeAuth subproject

Update readme files with SNS auth instructions

---

CHANGELOG.md
README-COMPOSE.md
README-JP.md
README.md
buildSrc/src/main/java/com/virtusize/android/constants/Constants.kt
gradle/libs.versions.toml
virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutter.kt
virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterImpl.kt
virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterPresenter.kt

Release 2.12.5
