virtusize/integration_android

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt, libsource/src/main/java/com/virtusize/libsource/data/local/BodyProfileRecommendedSizeParams.kt, libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeEnvironment.kt, libsource/src/main/java/com/virtusize/libsource/data/parsers/BodyProfileRecommendedSizeJsonParser.kt, libsource/src/main/java/com/virtusize/libsource/data/parsers/JsonUtils.kt, libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductAdditionalInfoJsonParser.kt, libsource/src/main/java/com/virtusize/libsource/data/parsers/StoreProductMetaJsonParser.kt, libsource/src/main/java/com/virtusize/libsource/data/remote/BodyProfileRecommendedSize.kt, libsource/src/main/java/com/virtusize/libsource/data/remote/Product.kt, libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProductAdditionalInfo.kt, libsource/src/main/java/com/virtusize/libsource/data/remote/StoreProductMeta.kt, libsource/src/main/java/com/virtusize/libsource/data/remote/UserBodyProfile.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt, libsource/src/test/java/com/virtusize/libsource/TestUtils.kt, libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt, libsource/src/test/java/com/virtusize/libsource/data/local/BodyProfileRecommendedSizeParamsTests.kt, libsource/src/test/java/com/virtusize/libsource/data/parsers/I18nLocalizationJsonParserTest.kt, libsource/src/test/java/com/virtusize/libsource/data/parsers/StoreProductAdditionalInfoJsonParserTest.kt, libsource/src/test/java/com/virtusize/libsource/data/parsers/StoreProductJsonParserTest.kt, libsource/src/test/java/com/virtusize/libsource/data/parsers/StoreProductMetaJsonParserTest.kt, libsource/src/test/java/com/virtusize/libsource/data/parsers/UserBodyProfileJsonParserTest.kt, libsource/src/test/java/com/virtusize/libsource/fixtures/ProductFixtures.kt, libsource/src/test/java/com/virtusize/libsource/fixtures/TestFixtures.kt, libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
=> Feature: Integrate Size Recommendation API

libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeEnvironment.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt, libsource/src/test/java/com/virtusize/libsource/VirtusizeTest.kt, libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTest.kt
=> Feature: Update the event API URL

libsource/src/main/java/com/virtusize/libsource/Virtusize.kt, libsource/src/main/java/com/virtusize/libsource/VirtusizeRepository.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeAPIService.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApi.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeEndpoint.kt, libsource/src/test/java/com/virtusize/libsource/network/VirtusizeAPIServiceTest.kt
When a user logs out of Aoyama, the SDK will make an API call to `/user-products` to re-fetch user items. The product list is expected to be empty from the server, but in fact, the product list includes the items that the user has created before they log in and then log out, which causes InPage does not display "Find the right size ..." when a user logs out.
=> Fix: the wrong InPage message when a user logs out

libsource/src/main/java/com/virtusize/libsource/VirtusizeRepository.kt, libsource/src/main/java/com/virtusize/libsource/data/local/VirtusizeErrorType.kt, libsource/src/main/java/com/virtusize/libsource/network/VirtusizeApiTask.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageStandard.kt, libsource/src/test/java/com/virtusize/libsource/network/VirtusizeAPIServiceTest.kt, libsource/src/test/java/com/virtusize/libsource/network/VirtusizeApiTaskTest.kt
The crash was caused by the `parseInputStreamAsObject` function in VirtusizeApiTask.kt returning a JSON string instead of returning null for **UserBodyProfile**. The `getBodyProfileRecommendedSize` function in VirtusizeRepository.kt required the type of userBodyProfile to be exactly **UserBodyProfile** but userBodyProfileResponse.successData that was passed into this function was a JSON string from `parseInputStreamAsObject`. Hence, an Exception was thrown.
=> Fix: the crash when a user's body profile is null

libsource/src/main/res/layout/view_inpage_standard.xml, libsource/src/main/res/values/dimens.xml
Make the range of the shadow a little bit smaller
Before
After
=> Fix: the shadow of InPage

libsource/src/main/java/com/virtusize/libsource/VirtusizeWebView.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeButton.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageMini.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeInPageStandard.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeView.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeWebViewFragment.kt, sampleAppKotlin/build.gradle, sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt, sampleAppKotlin/src/main/java/com/virtusize/android/SampleWebViewFragment.kt, sampleAppKotlin/src/main/res/layout/activity_main.xml, sampleAppKotlin/src/main/res/layout/webview_vs.xml
Create VirtusizeWebview which inherits from WebView for clients to use to solve the SNS popup issue in a web view.
The user login status is persistent even after the app restarts 👍
=> Feature: The SNS popup issue fix with the SDK

libsource/src/main/java/com/virtusize/libsource/VirtusizeWebView.kt, libsource/src/main/java/com/virtusize/libsource/ui/VirtusizeWebViewFragment.kt, sampleAppKotlin/build.gradle, sampleAppKotlin/src/main/java/com/virtusize/android/MainActivity.kt, sampleAppKotlin/src/main/java/com/virtusize/android/SampleWebViewFragment.kt, sampleAppKotlin/src/main/java/com/virtusize/android/WebViewFragment.kt
The SNS buttons are hidden by default when Aoyama is loaded in a web view.
To enable these buttons, the webview executes `window.virtusizeSNSEnabled = true;` when the webpage has finished loading.
**Before**
**After**
=> Feature: Enable SNS buttons for the Webview

sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/App.kt, virtusize-core/build.gradle, virtusize-core/src/main/java/com/virtusize/android/data/local/BodyProfileRecommendedSizeParams.kt, virtusize-core/src/main/java/com/virtusize/android/data/local/VirtusizeEnvironment.kt, virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApi.kt, virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApiTask.kt, virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeEndpoint.kt, virtusize-core/src/test/java/com/virtusize/android/data/local/BodyProfileRecommendedSizeParamsTests.kt, virtusize-core/src/test/java/com/virtusize/android/network/VirtusizeApiTest.kt, virtusize/build.gradle, virtusize/src/main/java/com/virtusize/android/VirtusizeRepository.kt, virtusize/src/main/java/com/virtusize/android/data/parsers/BodyProfileRecommendedSizeJsonParser.kt, virtusize/src/main/java/com/virtusize/android/data/remote/BodyProfileRecommendedSizeNew.kt, virtusize/src/main/java/com/virtusize/android/data/remote/VirtualItem.kt, virtusize/src/main/java/com/virtusize/android/data/remote/WillFitForSizes.kt, virtusize/src/main/java/com/virtusize/android/network/VirtusizeAPIService.kt, virtusize/src/test/java/com/virtusize/android/network/VirtusizeAPIServiceTest.kt
- Updated Size Recommendation API related URL, request model, response model.
- Added environment related size recommendation base URLs.
- Also did changes on test cases related to size recommendation API and verified it.
- Unit tested both the scenarios for male and female and their sizes.
N/A
https://app.clickup.com/t/3702259/NSDK-178
=> Update size recommendation endpoints

CHANGELOG.md, README-JP.md, README.md, build.gradle, gradle.properties, gradle/deploy.gradle, gradle/wrapper/gradle-wrapper.properties, sampleAppKotlin/src/main/java/com/virtusize/sampleappkotlin/WebViewFragment.kt, virtusize-core/build.gradle, virtusize-core/src/main/java/com/virtusize/android/data/local/BodyProfileRecommendedSizeParams.kt, virtusize/build.gradle, virtusize/src/main/java/com/virtusize/android/data/parsers/I18nLocalizationJsonParser.kt, virtusize/src/test/java/com/virtusize/android/data/parsers/I18nLocalizationJsonParserTest.kt
- Updated README.md and README-JP.md
- Updated Android Gradle plugin version to 8.5 and Gradle version to 8.7
https://developer.android.com/build/releases/gradle-plugin#updating-gradle
- Updated publishing gradle setup. Above Gradle 7.1, there's new publishing API https://developer.android.com/build/releases/past-releases/agp-7-1-0-release-notes#build-variant-publishing
https://developer.android.com/build/publish-library/configure-pub-variants
- Removed unused commented code
- Removed android.nonTransitiveRClass=false and android.nonFinalResIds=false in gradle.properties
There were some breaking changes in AGP 8.0, but it's not necessary to set them back to the old default values after fixing the R resource paths
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release- …
=> [NSDK-184] Hotfix - Update README.md and Gradle Build Files

.github/pull_request_template.md, sampleappcompose/src/main/java/com/virtusize/sampleapp/compose/VirtusizeSampleApp.kt, virtusize/src/main/java/com/virtusize/android/compose/theme/VirtusizeColors.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeButton.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeComposeViewModel.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/wip/VirtusizeButtonUiState.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/wip/VirtusizeButtonViewModel.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/wip/WIPVirtusizeButton.kt, virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterUtils.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeView.kt, virtusize/src/main/java/com/virtusize/android/util/VirtusizeUtils.kt
I decided to build the Jetpack Compose wrapper to compose the Android Views (VirtusizeButton, VirtusizeInPage, etc) we already have first before building Jetpack Compose UI components from scratch as it takes more time than expected. 
https://github.com/user-attachments/assets/5d68f2d0-0f8d-4473-8b5b-f08d595dd72d
=> [NSDK-193] Jetpack Compose AndroidView For VirtusizeButton

CHANGELOG.md, README-COMPOSE.md, sampleappcompose/build.gradle.kts, virtusize/build.gradle.kts, virtusize/src/main/java/com/virtusize/android/VirtusizeImpl.kt
The bug was caused by calling the session API endpoint multiple times for the same product, and somehow it cleared up the current logged-in user session.
- Prevented from calling the same API endpoint multiple times for the same product
https://github.com/user-attachments/assets/4ab2bc18-dd14-42d5-bc54-587805977db2
- Move declaring compose compiler version to the Virtusize module
- Updated README-COMPOSE.md
=> [NSDK-206] Fix an Issue Where the SDK Could Not Retain the Email Login Session

.github/workflows/publish.yml, .github/workflows/pull-request-checks.yml, CHANGELOG.md, gradle/libs.versions.toml, sampleAppKotlin/build.gradle.kts, sampleappcompose/build.gradle.kts, sampleappjava/build.gradle.kts, virtusize/build.gradle.kts
=> [NSDK-197] Bump Virtusize Auth SDK to 1.0.6

CHANGELOG.md, README-COMPOSE.md, README-JP.md, README.md, buildSrc/src/main/java/com/virtusize/android/constants/Constants.kt, gradle/libs.versions.toml, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
https://github.com/user-attachments/assets/b513c0fd-0cf0-46f1-bee1-1492396bd4de
https://github.com/user-attachments/assets/252e21ca-2071-461e-94b5-88297cb42f9f
=> [NSDK-235] Fix the Close Button on the Login Page

CHANGELOG.md, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
https://docs.google.com/presentation/d/1Cloxn7s0hsTMIDfznjPfBuXqAXMQUjXgKIwgyjoqk9c/edit#slide=id.g3210edc6694_0_5
- Password Reset button doesn’t work
- After the login is succeeded, you can never go back to the app automatically
https://github.com/user-attachments/assets/83dedd8e-da03-467b-9aa8-11caaae49d49
https://github.com/user-attachments/assets/1f615548-9f37-419c-a5c0-526fc84cea2f
=> [NSDK-245] Fix Password Reset Doesn’t Work and WebView Redirection Issue

CHANGELOG.md, gradle/libs.versions.toml, virtusize/build.gradle.kts, virtusize/src/main/java/com/virtusize/android/VirtusizeImpl.kt, virtusize/src/main/java/com/virtusize/android/VirtusizeRepository.kt
- Product loading takes a while (3-4 seconds), due to sequential API requests
=> Optimize product loading time

CHANGELOG.md, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
- SNS still visible even thought `.setShowSNSButtons(false)` configured
=> Ensure SNS buttons are hidden when configured to do so

CHANGELOG.md, virtusize-core/src/main/java/com/virtusize/android/network/VirtusizeApi.kt, virtusize-core/src/test/java/com/virtusize/android/network/VirtusizeApiTest.kt
- Product Types always loaded from the origin server, while it's data persistent and could be easily cached
=> Use cache-friendly endpoint to load product types

README-COMPOSE.md, README-JP.md, README.md, buildSrc/src/main/java/com/virtusize/android/constants/Constants.kt, gradle/libs.versions.toml
The version number is still 2.11.1
=> Fix release 2.12.0

CHANGELOG.md, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeInpPageStandard.kt
Fix shadow clipping in compose version of VirtusizeInPageStandard; 
Update preview of VirtusizeInPageStandatd to better reflect the changes;
=> Fix shadow clipping in VirtusizeInPageStandard

CHANGELOG.md, virtusize/src/main/java/com/virtusize/android/Virtusize.kt, virtusize/src/main/java/com/virtusize/android/VirtusizeImpl.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeButton.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeInPageMini.kt, virtusize/src/main/java/com/virtusize/android/compose/ui/VirtusizeInpPageStandard.kt
Fix memory leak in `VirtusizeImpl.virtusizeViews`;
Add `Virtusize.getInstanceOrNull()` to better support lazy scenarios;
When using Virtusize composables, underlying `VirtusizeView`s (which are regular Android views) insances are stored in the `VirtusizeImpl` singleton in `virtusizeViews` and are never released, causing them to leak
`VirtusizeView` isntances are removed form the singleton after Virtusize composables leave the composition, allowing them to be garbage collected.
=> Fix memory leak in VirtusizeImpl.virtusizeViews

CHANGELOG.md, virtusize/src/main/res/values-ja/strings.xml, virtusize/src/main/res/values-ko/strings.xml, virtusize/src/main/res/values/strings.xml
Virtusize SDK's inpage buttons text is not the same as in web version.
=> Align Virtusize button texts with Aoyama

CHANGELOG.md, virtusize-core/src/main/java/com/virtusize/android/data/local/VirtusizeEvent.kt, virtusize/src/main/java/com/virtusize/android/Virtusize.kt, virtusize/src/main/java/com/virtusize/android/VirtusizeImpl.kt, virtusize/src/main/java/com/virtusize/android/VirtusizeRepository.kt, virtusize/src/main/java/com/virtusize/android/data/parsers/VirtusizeEventJsonParser.kt, virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterImpl.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeButton.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeInPageMini.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeInPageStandard.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeInPageView.kt, virtusize/src/main/java/com/virtusize/android/ui/VirtusizeWebViewFragment.kt
Explain the current situation of the code
- Changing language on web is not reflected in Virtusize widgets
=> Handle user-clicked-language event

CHANGELOG.md, virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutter.kt, virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterImpl.kt, virtusize/src/main/java/com/virtusize/android/flutter/VirtusizeFlutterPresenter.kt
Language change event on web is not handled in Flutter SDK buttons.
Flutter SDK handles the language change event on web.
=> Handle language change on web in Flutter SDK implementation

CHANGELOG.md, README-COMPOSE.md, README-JP.md, README.md, buildSrc/src/main/java/com/virtusize/android/constants/Constants.kt, gradle.properties, gradle/libs.versions.toml
According to Google Play’s review requirements, all apps targeting Android 15 and above are required to support a memory page size of 16KB.
Added Android 15+ support memory page size of 16KB
=> Add Android 15+ support memory page size of 16KB
